### ISSUE TITLE
Wrong absolute path of source-map-support at build time

### ISSUE THREAD

**Issue by mxfs** [palmerhq/backpack#41]
Seems to be an escape problem at the time of parsing. (backpack-core version **0.0.9**)

The backslashs from requrie.resolve is scaped on build time and escaped again at runtime.
I use Windows and the implementation of source-map-support in version **0.0.8** works well

**Expected:** `C:\\Users\\Name\\Dir\\Project\\node_modules\\source-map-support\\source-map-support.js`

**Currently built and fails:**
![Image](http://image.prntscr.com/image/2d20b606221b414bbeb111f30d5eae48.png)

**Error log:**

DONE  Compiled successfully in 321ms

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:UsersNameDirProject
ode_modulessource-map-supportsource-map-support.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Name\Dir\Project\build\main.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by jaredpalmer** [comment]
Can you try with 0.1.0 ? Are you still getting this error on windows?

**Comment by mxfs** [comment]
0.1.0 works fine thanks!
